// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: johnjud/backend/adopt/v1/adopt.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Adopt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	PetId  string `protobuf:"bytes,3,opt,name=petId,proto3" json:"petId,omitempty"`
}

func (x *Adopt) Reset() {
	*x = Adopt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Adopt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Adopt) ProtoMessage() {}

func (x *Adopt) ProtoReflect() protoreflect.Message {
	mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Adopt.ProtoReflect.Descriptor instead.
func (*Adopt) Descriptor() ([]byte, []int) {
	return file_johnjud_backend_adopt_v1_adopt_proto_rawDescGZIP(), []int{0}
}

func (x *Adopt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Adopt) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Adopt) GetPetId() string {
	if x != nil {
		return x.PetId
	}
	return ""
}

type FindAllAdoptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FindAllAdoptRequest) Reset() {
	*x = FindAllAdoptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAdoptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAdoptRequest) ProtoMessage() {}

func (x *FindAllAdoptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAdoptRequest.ProtoReflect.Descriptor instead.
func (*FindAllAdoptRequest) Descriptor() ([]byte, []int) {
	return file_johnjud_backend_adopt_v1_adopt_proto_rawDescGZIP(), []int{1}
}

type FindAllAdoptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adopts []*Adopt `protobuf:"bytes,1,rep,name=adopts,proto3" json:"adopts,omitempty"`
}

func (x *FindAllAdoptResponse) Reset() {
	*x = FindAllAdoptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAllAdoptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllAdoptResponse) ProtoMessage() {}

func (x *FindAllAdoptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllAdoptResponse.ProtoReflect.Descriptor instead.
func (*FindAllAdoptResponse) Descriptor() ([]byte, []int) {
	return file_johnjud_backend_adopt_v1_adopt_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllAdoptResponse) GetAdopts() []*Adopt {
	if x != nil {
		return x.Adopts
	}
	return nil
}

type CreateAdoptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adopt *Adopt `protobuf:"bytes,1,opt,name=adopt,proto3" json:"adopt,omitempty"`
}

func (x *CreateAdoptRequest) Reset() {
	*x = CreateAdoptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdoptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdoptRequest) ProtoMessage() {}

func (x *CreateAdoptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdoptRequest.ProtoReflect.Descriptor instead.
func (*CreateAdoptRequest) Descriptor() ([]byte, []int) {
	return file_johnjud_backend_adopt_v1_adopt_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAdoptRequest) GetAdopt() *Adopt {
	if x != nil {
		return x.Adopt
	}
	return nil
}

type CreateAdoptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adopt *Adopt `protobuf:"bytes,1,opt,name=adopt,proto3" json:"adopt,omitempty"`
}

func (x *CreateAdoptResponse) Reset() {
	*x = CreateAdoptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdoptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdoptResponse) ProtoMessage() {}

func (x *CreateAdoptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdoptResponse.ProtoReflect.Descriptor instead.
func (*CreateAdoptResponse) Descriptor() ([]byte, []int) {
	return file_johnjud_backend_adopt_v1_adopt_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAdoptResponse) GetAdopt() *Adopt {
	if x != nil {
		return x.Adopt
	}
	return nil
}

type DeleteAdoptRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAdoptRequest) Reset() {
	*x = DeleteAdoptRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdoptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdoptRequest) ProtoMessage() {}

func (x *DeleteAdoptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdoptRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdoptRequest) Descriptor() ([]byte, []int) {
	return file_johnjud_backend_adopt_v1_adopt_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAdoptRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAdoptResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteAdoptResponse) Reset() {
	*x = DeleteAdoptResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdoptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdoptResponse) ProtoMessage() {}

func (x *DeleteAdoptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdoptResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdoptResponse) Descriptor() ([]byte, []int) {
	return file_johnjud_backend_adopt_v1_adopt_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAdoptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_johnjud_backend_adopt_v1_adopt_proto protoreflect.FileDescriptor

var file_johnjud_backend_adopt_v1_adopt_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2f, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x6f, 0x70, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2e,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76, 0x31,
	0x22, 0x45, 0x0a, 0x05, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x65, 0x74, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x41,
	0x6c, 0x6c, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4f,
	0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x06, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x73, 0x22,
	0x4b, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2e, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x05, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x22, 0x4c, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x05, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x6f, 0x70, 0x74, 0x52, 0x05, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x32, 0xcc, 0x02, 0x0a, 0x0c, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x6a, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x12, 0x2d, 0x2e,
	0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e,
	0x61, 0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c,
	0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x6a,
	0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61,
	0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x41,
	0x64, 0x6f, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2c, 0x2e, 0x6a, 0x6f, 0x68, 0x6e, 0x6a,
	0x75, 0x64, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6f, 0x70, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64,
	0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x2c, 0x2e, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2e, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2e, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2d, 0x2e, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e,
	0x64, 0x2e, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x64, 0x6f, 0x70, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x1a, 0x5a, 0x18, 0x6a, 0x6f, 0x68, 0x6e, 0x6a, 0x75, 0x64, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x61, 0x64, 0x6f, 0x70, 0x74, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_johnjud_backend_adopt_v1_adopt_proto_rawDescOnce sync.Once
	file_johnjud_backend_adopt_v1_adopt_proto_rawDescData = file_johnjud_backend_adopt_v1_adopt_proto_rawDesc
)

func file_johnjud_backend_adopt_v1_adopt_proto_rawDescGZIP() []byte {
	file_johnjud_backend_adopt_v1_adopt_proto_rawDescOnce.Do(func() {
		file_johnjud_backend_adopt_v1_adopt_proto_rawDescData = protoimpl.X.CompressGZIP(file_johnjud_backend_adopt_v1_adopt_proto_rawDescData)
	})
	return file_johnjud_backend_adopt_v1_adopt_proto_rawDescData
}

var file_johnjud_backend_adopt_v1_adopt_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_johnjud_backend_adopt_v1_adopt_proto_goTypes = []interface{}{
	(*Adopt)(nil),                // 0: johnjud.backend.adopt.v1.Adopt
	(*FindAllAdoptRequest)(nil),  // 1: johnjud.backend.adopt.v1.FindAllAdoptRequest
	(*FindAllAdoptResponse)(nil), // 2: johnjud.backend.adopt.v1.FindAllAdoptResponse
	(*CreateAdoptRequest)(nil),   // 3: johnjud.backend.adopt.v1.CreateAdoptRequest
	(*CreateAdoptResponse)(nil),  // 4: johnjud.backend.adopt.v1.CreateAdoptResponse
	(*DeleteAdoptRequest)(nil),   // 5: johnjud.backend.adopt.v1.DeleteAdoptRequest
	(*DeleteAdoptResponse)(nil),  // 6: johnjud.backend.adopt.v1.DeleteAdoptResponse
}
var file_johnjud_backend_adopt_v1_adopt_proto_depIdxs = []int32{
	0, // 0: johnjud.backend.adopt.v1.FindAllAdoptResponse.adopts:type_name -> johnjud.backend.adopt.v1.Adopt
	0, // 1: johnjud.backend.adopt.v1.CreateAdoptRequest.adopt:type_name -> johnjud.backend.adopt.v1.Adopt
	0, // 2: johnjud.backend.adopt.v1.CreateAdoptResponse.adopt:type_name -> johnjud.backend.adopt.v1.Adopt
	1, // 3: johnjud.backend.adopt.v1.AdoptService.FindAll:input_type -> johnjud.backend.adopt.v1.FindAllAdoptRequest
	3, // 4: johnjud.backend.adopt.v1.AdoptService.Create:input_type -> johnjud.backend.adopt.v1.CreateAdoptRequest
	5, // 5: johnjud.backend.adopt.v1.AdoptService.Delete:input_type -> johnjud.backend.adopt.v1.DeleteAdoptRequest
	2, // 6: johnjud.backend.adopt.v1.AdoptService.FindAll:output_type -> johnjud.backend.adopt.v1.FindAllAdoptResponse
	4, // 7: johnjud.backend.adopt.v1.AdoptService.Create:output_type -> johnjud.backend.adopt.v1.CreateAdoptResponse
	6, // 8: johnjud.backend.adopt.v1.AdoptService.Delete:output_type -> johnjud.backend.adopt.v1.DeleteAdoptResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_johnjud_backend_adopt_v1_adopt_proto_init() }
func file_johnjud_backend_adopt_v1_adopt_proto_init() {
	if File_johnjud_backend_adopt_v1_adopt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Adopt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAdoptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAllAdoptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdoptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdoptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAdoptRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_johnjud_backend_adopt_v1_adopt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAdoptResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_johnjud_backend_adopt_v1_adopt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_johnjud_backend_adopt_v1_adopt_proto_goTypes,
		DependencyIndexes: file_johnjud_backend_adopt_v1_adopt_proto_depIdxs,
		MessageInfos:      file_johnjud_backend_adopt_v1_adopt_proto_msgTypes,
	}.Build()
	File_johnjud_backend_adopt_v1_adopt_proto = out.File
	file_johnjud_backend_adopt_v1_adopt_proto_rawDesc = nil
	file_johnjud_backend_adopt_v1_adopt_proto_goTypes = nil
	file_johnjud_backend_adopt_v1_adopt_proto_depIdxs = nil
}
